name: mobile
description: JB GestÃ£o.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.1.2
  animated_splash_screen: ^1.3.0
  timeline_tile: ^2.0.0
  dio: ^5.3.3
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^23.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo.png
    - assets/icon.png